server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/couple-diary
    username: root
    password: root
    hikari:
      max-lifetime: 57000
      maximum-pool-size: 24
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 68895080890-e0ktqa21oo6d1jssli31730jkmccucgl.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email